name: 构建玩客云uboot[rmoyulong修改]

on:
  #自动编译：每天早上4点
  #schedule:
    #- cron: 0 20 * * *
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查项目
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install make imagemagick

      - name: 下载依赖
        run: |
          curl -L -O https://redirect.armbian.com/_toolchain/gcc-linaro-arm-none-eabi-4.8-2014.04_linux.tar.xz
          tar xvf ./gcc-linaro-arm-none-eabi-4.8-2014.04_linux.tar.xz

      - name: 编译
        run: |
          export PATH="$PATH:$(pwd)/gcc-linaro-arm-none-eabi-4.8-2014.04_linux/bin"

          make distclean
          make m8b_onecloud_config
          make -j$(nproc)

      - name: 下载 AmlImg
        run: |
          ver="v0.3.0"
          curl -L -o ./AmlImg https://github.com/hzyitc/AmlImg/releases/download/$ver/AmlImg_${ver}_linux_amd64
          chmod +x ./AmlImg

      - name: 生成资源
        run: |
          mkdir -p resource

          convert \
            -size 640x360 \
            -background black \
            -gravity center -font "DejaVu-Sans" -pointsize 64 -fill white label:"U-Boot" \
            BMP3:resource/bootup.bmp

          cat <<EOF >resource/list.txt
          090000:bootup:bootup.bmp
          EOF
          ./AmlImg res_pack build/resource.img resource/

      - name: 生成 eMMC 直刷底包
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWRT_DATE: $(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
        run: |
          mkdir -p pack

          cp build/ddr_init.bin pack/DDR.USB
          cp build/u-boot-comp.bin pack/UBOOT_COMP.USB

          cat <<EOF >pack/aml_sdc_burn.ini
          [common]
          erase_bootloader    = 1
          erase_flash         = 0
          reboot              = 0

          ;package will filled by sdacard burning tool
          [burn_ex]
          package     = aml_upgrade_package.img
          ;media       =
          EOF

          cat <<EOF >pack/platform.conf
          Platform:0x0801
          BinPara:0xd9010000
          DDRLoad:0xd9000000
          DDRRun:0xd9000030
          Uboot_down:0x200000
          Uboot_decomp:0xd9000030
          EOF

          cp build/u-boot.bin pack/bootloader.img
          echo -n "sha1sum $(sha1sum pack/bootloader.img | awk '{print $1}')" >pack/bootloader.VERIFY

          cp build/resource.img pack/resource.img
          echo -n "sha1sum $(sha1sum pack/resource.img | awk '{print $1}')" >pack/resource.VERIFY

          cat <<EOF >pack/commands.txt
          USB:DDR:normal:DDR.USB
          USB:UBOOT_COMP:normal:UBOOT_COMP.USB

          ini:aml_sdc_burn:normal:aml_sdc_burn.ini
          conf:platform:normal:platform.conf

          PARTITION:bootloader:normal:bootloader.img
          VERIFY:bootloader:normal:bootloader.VERIFY

          PARTITION:resource:normal:resource.img
          VERIFY:resource:normal:resource.VERIFY

          # PARTITION:boot:normal:boot.img
          # VERIFY:boot:normal:boot.VERIFY
          # PARTITION:rootfs:normal:rootfs.img
          # VERIFY:rootfs:normal:rootfs.VERIFY
          EOF

          ./AmlImg pack build/eMMC.burn.img pack/
          
          #信息
          export OWRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          echo "OWRT_DATE=$OWRT_DATE" >> $GITHUB_ENV
          
      - name: 整理固件
        run: |
        mkdir -p outfile
        sudo cp build/*.bin ./outfile
        sudo cp build/resource.img ./outfile
        sudo cp build/eMMC.burn.img ./outfile

      - name: 上传EMMC直刷底包
        uses: rmoyulong/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Onecloud_Uboot_${{ env.OWRT_DATE }}
          files: outfile/*
          body: |
            自用玩客云直刷底包eMMC.burn.img！刷写底包将抹去所有信息！
            =============基本信息============

            源码：https://github.com/hzyitc/u-boot-onecloud
            平台：liunx/armv7
